In [1]:
import pandas as pd

tips = pd.read_csv("https://milliams.com/courses/data_analysis_python/tips.csv")
tips

     total_bill   tip   day    time  size
0         16.99  0.71   Sun  Dinner     2
1         10.34  1.16   Sun  Dinner     3
2         21.01  2.45   Sun  Dinner     3
3         23.68  2.32   Sun  Dinner     2
4         24.59  2.53   Sun  Dinner     4
..          ...   ...   ...     ...   ...
239       29.03  4.14   Sat  Dinner     3
240       27.18  1.40   Sat  Dinner     2
241       22.67  1.40   Sat  Dinner     2
242       17.82  1.22   Sat  Dinner     2
243       18.78  2.10  Thur  Dinner     2

[244 rows x 5 columns]

In [2]:
thurs = tips[tips["day"] == "Thur"]
thurs

     total_bill   tip   day    time  size
77        27.20  2.80  Thur   Lunch     4
78        22.76  2.10  Thur   Lunch     2
79        17.29  1.90  Thur   Lunch     2
80        19.44  2.10  Thur   Lunch     2
81        16.66  2.38  Thur   Lunch     2
..          ...   ...   ...     ...   ...
202       13.00  1.40  Thur   Lunch     2
203       16.40  1.75  Thur   Lunch     2
204       20.53  2.80  Thur   Lunch     4
205       16.47  2.26  Thur   Lunch     3
243       18.78  2.10  Thur  Dinner     2

[62 rows x 5 columns]

In [3]:
thurs["tip"].mean()

np.float64(1.9398387096774192)

In [4]:
tips[tips["day"] == "Sat"]["tip"].mean()

np.float64(2.095402298850575)

In [5]:
tips[tips["total_bill"] < 8]

     total_bill   tip   day    time  size
67         3.07  0.70   Sat  Dinner     1
92         5.75  0.70   Fri  Dinner     2
111        7.25  0.70   Sat  Dinner     1
149        7.51  1.40  Thur   Lunch     2
172        7.25  3.60   Sun  Dinner     2
195        7.56  1.01  Thur   Lunch     2
218        7.74  1.01   Sat  Dinner     2

In [6]:
tips[tips["size"] >= 5]

     total_bill   tip   day    time  size
125       29.80  2.94  Thur   Lunch     6
141       34.30  4.69  Thur   Lunch     6
142       41.19  3.50  Thur   Lunch     5
143       27.05  3.50  Thur   Lunch     6
155       29.85  3.60   Sun  Dinner     5
156       48.17  3.50   Sun  Dinner     6
185       20.69  3.50   Sun  Dinner     5
187       30.46  1.40   Sun  Dinner     5
216       28.15  2.10   Sat  Dinner     5

In [7]:
tips[(tips["day"] == "Sat") & (tips["total_bill"] < 8)]

     total_bill   tip  day    time  size
67         3.07  0.70  Sat  Dinner     1
111        7.25  0.70  Sat  Dinner     1
218        7.74  1.01  Sat  Dinner     2

In [8]:
tips[(tips["time"] == "Lunch") & (tips["size"] >= 4)]

     total_bill   tip   day   time  size
77        27.20  2.80  Thur  Lunch     4
85        34.83  3.62  Thur  Lunch     4
119       24.08  2.04  Thur  Lunch     4
125       29.80  2.94  Thur  Lunch     6
141       34.30  4.69  Thur  Lunch     6
142       41.19  3.50  Thur  Lunch     5
143       27.05  3.50  Thur  Lunch     6
197       43.11  3.50  Thur  Lunch     4
204       20.53  2.80  Thur  Lunch     4

In [9]:
sat_filter = tips["day"] == "Sat"
tips.loc[sat_filter]        # same as tips[sat_filter]

tips.loc[:, "size"]         # same as tips["size"]

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64